const DEMO_PRODUCTS = [
  {
    id: 1,
    title: "Summer Breeze Shirt",
    price: 25.99,
    description: "A light and airy shirt perfect for summer outings.",
    image: "https://via.placeholder.com/250x220",
    season: "Summer",
  },
  {
    id: 2,
    title: "Winter Warmer Jacket",
    price: 89.99,
    description: "A cozy jacket to keep you warm during chilly winters.",
    image: "https://via.placeholder.com/250x220",
    season: "Winter",
  },
  {
    id: 3,
    title: "Spring Bloom Dress",
    price: 45.99,
    description: "A floral dress that celebrates the beauty of spring.",
    image: "https://via.placeholder.com/250x220",
    season: "Spring",
  },
  {
    id: 4,
    title: "Autumn Trail Boots",
    price: 64.99,
    description: "Sturdy boots for trekking through autumn leaves.",
    image: "https://via.placeholder.com/250x220",
    season: "Autumn",
  },
  {
    id: 5,
    title: "Summer Splash Sandals",
    price: 19.99,
    description: "Comfortable sandals perfect for the beach.",
    image: "https://via.placeholder.com/250x220",
    season: "Summer",
  },
  {
    id: 6,
    title: "Winter Snow Gloves",
    price: 14.99,
    description: "Thick gloves designed for snowy adventures.",
    image: "https://via.placeholder.com/250x220",
    season: "Winter",
  },
  {
    id: 7,
    title: "Spring Meadow Hat",
    price: 22.99,
    description: "A stylish hat ideal for sunny spring days.",
    image: "https://via.placeholder.com/250x220",
    season: "Spring",
  },
  {
    id: 8,
    title: "Autumn Chill Sweater",
    price: 39.99,
    description: "A cozy sweater to stay warm during fall.",
    image: "https://via.placeholder.com/250x220",
    season: "Autumn",
  },
  {
    id: 9,
    title: "Summer Surf Shorts",
    price: 29.99,
    description: "Quick-drying shorts perfect for surfing.",
    image: "https://via.placeholder.com/250x220",
    season: "Summer",
  },
  {
    id: 10,
    title: "Winter Frost Scarf",
    price: 12.99,
    description: "A thick scarf to keep the cold away.",
    image: "https://via.placeholder.com/250x220",
    season: "Winter",
  },
  {
    id: 11,
    title: "Spring Picnic Blanket",
    price: 35.99,
    description: "A colorful blanket for springtime picnics.",
    image: "https://via.placeholder.com/250x220",
    season: "Spring",
  },
  {
    id: 12,
    title: "Autumn Breeze Beanie",
    price: 18.99,
    description: "A snug beanie perfect for crisp autumn days.",
    image: "https://via.placeholder.com/250x220",
    season: "Autumn",
  },
  {
    id: 13,
    title: "Summer Adventure Backpack",
    price: 49.99,
    description: "A lightweight backpack for summer hikes.",
    image: "https://via.placeholder.com/250x220",
    season: "Summer",
  },
  {
    id: 14,
    title: "Winter Wonderland Boots",
    price: 79.99,
    description: "Warm and waterproof boots for winter.",
    image: "https://via.placeholder.com/250x220",
    season: "Winter",
  },
  {
    id: 15,
    title: "Spring Butterfly Brooch",
    price: 14.99,
    description: "A delicate brooch with a butterfly motif.",
    image: "https://via.placeholder.com/250x220",
    season: "Spring",
  },
  {
    id: 16,
    title: "Autumn Hike Vest",
    price: 59.99,
    description: "A versatile vest for fall outdoor activities.",
    image: "https://via.placeholder.com/250x220",
    season: "Autumn",
  },
  {
    id: 17,
    title: "Summer Festival Hat",
    price: 19.99,
    description: "A wide-brimmed hat for sunny days.",
    image: "https://via.placeholder.com/250x220",
    season: "Summer",
  },
  {
    id: 18,
    title: "Winter Snuggle Blanket",
    price: 39.99,
    description: "A plush blanket for cozy winter nights.",
    image: "https://via.placeholder.com/250x220",
    season: "Winter",
  },
  {
    id: 19,
    title: "Spring Petal Scarf",
    price: 24.99,
    description: "A lightweight scarf for spring breezes.",
    image: "https://via.placeholder.com/250x220",
    season: "Spring",
  },
  {
    id: 20,
    title: "Autumn Pumpkin Candle",
    price: 14.99,
    description: "A candle that brings the scent of fall indoors.",
    image: "https://via.placeholder.com/250x220",
    season: "Autumn",
  },
];
export default DEMO_PRODUCTS;
