const DEMO_PRODUCTS = [
  {
    _id: 1,
    name: "Summer Breeze Shirt",
    brand: "Donix",
    price: 25.99,
    description: "A light and airy shirt perfect for summer outings.",
    images: ["https://placehold.co/220x220"],
    season: "Summer",
  },
  {
    _id: 2,
    name: "Winter Warmer Jacket",
    brand: "Donix",
    price: 89.99,
    description: "A cozy jacket to keep you warm during chilly winters.",
    images: ["https://placehold.co/220x220"],
    season: "Winter",
  },
  {
    _id: 3,
    name: "Spring Bloom Dress",
    brand: "Donix",
    price: 45.99,
    description: "A floral dress that celebrates the beauty of spring.",
    images: ["https://placehold.co/220x220"],
    season: "Spring",
  },
  {
    _id: 4,
    name: "Autumn Trail Boots",
    brand: "Donix",
    price: 64.99,
    description: "Sturdy boots for trekking through autumn leaves.",
    images: ["https://placehold.co/220x220"],
    season: "Autumn",
  },
  {
    _id: 5,
    name: "Summer Splash Sandals",
    brand: "Donix",
    price: 19.99,
    description: "Comfortable sandals perfect for the beach.",
    images: ["https://placehold.co/220x220"],
    season: "Summer",
  },
  {
    _id: 6,
    name: "Winter Snow Gloves",
    brand: "Donix",
    price: 14.99,
    description: "Thick gloves designed for snowy adventures.",
    images: ["https://placehold.co/220x220"],
    season: "Winter",
  },
  {
    _id: 7,
    name: "Spring Meadow Hat",
    brand: "Donix",
    price: 22.99,
    description: "A stylish hat _ideal for sunny spring days.",
    images: ["https://placehold.co/220x220"],
    season: "Spring",
  },
  {
    _id: 8,
    name: "Autumn Chill Sweater",
    brand: "Donix",
    price: 39.99,
    description: "A cozy sweater to stay warm during fall.",
    images: ["https://placehold.co/220x220"],
    season: "Autumn",
  },
  {
    _id: 9,
    name: "Summer Surf Shorts",
    brand: "Donix",
    price: 29.99,
    description: "Quick-drying shorts perfect for surfing.",
    images: ["https://placehold.co/220x220"],
    season: "Summer",
  },
  {
    _id: 10,
    name: "Winter Frost Scarf",
    brand: "Donix",
    price: 12.99,
    description: "A thick scarf to keep the cold away.",
    images: ["https://placehold.co/220x220"],
    season: "Winter",
  },
  {
    _id: 11,
    name: "Spring Picnic Blanket",
    brand: "Donix",
    price: 35.99,
    description: "A colorful blanket for springtime picnics.",
    images: ["https://placehold.co/220x220"],
    season: "Spring",
  },
  {
    _id: 12,
    name: "Autumn Breeze Beanie",
    brand: "Donix",
    price: 18.99,
    description: "A snug beanie perfect for crisp autumn days.",
    images: ["https://placehold.co/220x220"],
    season: "Autumn",
  },
  {
    _id: 13,
    name: "Summer Adventure Backpack",
    brand: "Donix",
    price: 49.99,
    description: "A lightweight backpack for summer hikes.",
    images: ["https://placehold.co/220x220"],
    season: "Summer",
  },
  {
    _id: 14,
    name: "Winter Wonderland Boots",
    brand: "Donix",
    price: 79.99,
    description: "Warm and waterproof boots for winter.",
    images: ["https://placehold.co/220x220"],
    season: "Winter",
  },
  {
    _id: 15,
    name: "Spring Butterfly Brooch",
    brand: "Donix",
    price: 14.99,
    description: "A delicate brooch with a butterfly motif.",
    images: ["https://placehold.co/220x220"],
    season: "Spring",
  },
  {
    _id: 16,
    name: "Autumn Hike Vest",
    brand: "Donix",
    price: 59.99,
    description: "A versatile vest for fall outdoor activities.",
    images: ["https://placehold.co/220x220"],
    season: "Autumn",
  },
  {
    _id: 17,
    name: "Summer Festival Hat",
    brand: "Donix",
    price: 19.99,
    description: "A w_ide-brimmed hat for sunny days.",
    images: ["https://placehold.co/220x220"],
    season: "Summer",
  },
  {
    _id: 18,
    name: "Winter Snuggle Blanket",
    brand: "Donix",
    price: 39.99,
    description: "A plush blanket for cozy winter nights.",
    images: ["https://placehold.co/220x220"],
    season: "Winter",
  },
  {
    _id: 19,
    name: "Spring Petal Scarf",
    brand: "Donix",
    price: 24.99,
    description: "A lightweight scarf for spring breezes.",
    images: ["https://placehold.co/220x220"],
    season: "Spring",
  },
  {
    _id: 20,
    name: "Autumn Pumpkin Candle",
    brand: "Donix",
    price: 14.99,
    description: "A candle that brings the scent of fall indoors.",
    images: ["https://placehold.co/220x220"],
    season: "Autumn",
  },
];
export default DEMO_PRODUCTS;
